export { InfoRootComponent } from './info-root.component';
export { InfoInicioComponent } from './info-inicio.component';
export { InfoContactoComponent } from './info-contacto.component';
export { InfoFaqComponent } from './info-faq.component';
export { InfoFormacionComponent } from './info-formacion.component';
export { InfoGaleriaComponent } from './info-galeria.component';
export { InfoHistoriaComponent } from './info-historia.component';
export { InfoSitiosComponent } from './info-sitios.component';
export { InfoTesisComponent } from './info-tesis.component';
